import { ArrowLeft, AlertOctagon, Clock, IdCard, Sparkles } from 'lucide-react'
import type { WorkOrder } from '@/data/types'
import { Badge } from './ui/Badge'

interface Props {
  wo: WorkOrder
}

function timeAgo(iso: string) {
  const diff = Date.now() - new Date(iso).getTime()
  const mins = Math.max(1, Math.round(diff / 60000))
  if (mins < 60) return `${mins} min ago`
  const hrs = Math.round(mins / 60)
  if (hrs < 24) return `${hrs} hr${hrs === 1 ? '' : 's'} ago`
  const days = Math.round(hrs / 24)
  return `${days} day${days === 1 ? '' : 's'} ago`
}

/** Count of fields the AI auto-populated on this passport. Used in the byline. */
function autoFilledFieldCount(wo: WorkOrder) {
  const ai = wo.aiAnalysis
  let n = 0
  if (ai.rationale.length) n++                   // Category & triage
  if (ai.descriptionOfServices) n++              // Description of services
  if (ai.predictedLineItems.length) n++          // Line items
  if (ai.similarWOs.length) n++                  // Similar WOs
  if (ai.recommendedVendor) n++                  // Vendor
  if (ai.estimatedTotalCost) n++                 // Cost
  if (ai.estimatedResolutionHours) n++           // ETA
  if (ai.goldenPathScore) n++                    // Score
  if (wo.goldenPath.length) n++                  // Pipeline plan
  return n
}

export function WoHeader({ wo }: Props) {
  const fieldCount = autoFilledFieldCount(wo)
  return (
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-start gap-4 px-6 py-4">
        <button className="mt-1 flex h-9 w-9 flex-none items-center justify-center rounded-lg text-slate-500 hover:bg-slate-100 hover:text-slate-900">
          <ArrowLeft className="h-4 w-4" />
        </button>
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <span className="inline-flex items-center gap-1.5 rounded-md bg-brand-50 px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wider text-brand-700 ring-1 ring-brand-200">
              <IdCard className="h-3.5 w-3.5" /> Work Order Passport
            </span>
            <span className="font-mono text-xs text-slate-500">{wo.id}</span>
            {wo.priority === 'urgent' && (
              <Badge variant="urgent">
                <AlertOctagon className="h-3 w-3" /> Urgent · P1
              </Badge>
            )}
            {wo.priority === 'high' && <Badge variant="high">High · P2</Badge>}
            {wo.priority === 'normal' && <Badge variant="normal">Normal</Badge>}
            <span className="inline-flex items-center gap-1 text-xs text-slate-500">
              <Clock className="h-3 w-3" /> Created {timeAgo(wo.createdAt)}
            </span>
          </div>
          <h1 className="mt-1.5 truncate text-xl font-semibold text-slate-900">{wo.title}</h1>
          <div className="mt-1 inline-flex items-center gap-1.5 text-[11px] text-slate-500">
            <Sparkles className="h-3 w-3 text-brand-500" />
            <span>
              Passport generated by AI · <span className="font-semibold text-slate-700">{fieldCount} fields</span> auto-filled from photos, history &amp; asset record
            </span>
          </div>
        </div>
      </div>
    </header>
  )
}
